version: '3'
services:
  app:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    env_file:
    - .env
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
      - "3001:3001"
    command: ["nodemon", "src/index.js"]
    user: "1000"